Orderers heavy cleanup
filecoin-project/mir pull request #436
Opened 2023-05-08 02:32 UTC by ranchalp

This PR is a quite heavy clean up (refactorization) of the orderers module. 
In short: 

- `internal/parts` holds the protocol logic, separated in three subparts (`viewchange, goodcase and catchup`)
- `internal/common` holds state that is internally common to all the three subparts of the module 
- `common` holds state that is common to both the module and used outside the module

Note that this partitioning can be subject to modifications, but there are limitations once one starts subdividing module logic (to avoid cyclic imports). 

Anticipating a possible comment: I initially tried to inline all functions for easier readability (similarly to the availability module) by removing redundant calls to auxiliary functions in the `Upon...` methods. Once I completed this, I am left with the doubt of whether this is always more readable than having `apply...` auxiliary functions as only body of the `Upon...` methods. I think that if the `Upon...` is easy to follow and part of the core logic then leaving it inline makes sense, but otherwise can be left to be treated with an auxiliary function.

In fact, inlining all of this has left the viewchange logic so big that there is a lint error (reason for which lint fails currently). So this is very much open for the reviewer to discuss (as many other things surely).

2023-05-09 13:09 UTC, matejpavlovic requested changes
Thanks for the heavy lifting here!
All directly requested changes are of cosmetic character.
I left some other comments, on the other hand, that request changes best addressed in separate PRs. So feel free to just create corresponding issues and not modify the code for now.

Regarding the complexity of the function handlers that are, technically, all in a single go function, I see your point and I agree that currently it is sub-optimal. Here's my suggestion:

Let's pick one way of approaching this per file. Either
1. everything is in-line, i.e., inside the `Upon...` handler registration call, as an anonymous function, the way simple stuff like the the availability module (auxiliary functions are still encouraged, but the high-level logic of a handler would be directly inside the handler), or
2. all handler registrations would be one-liners, simply referring to auxiliary handler functions *of the same name*$^1$ (but with a lower-case first letter, to not export them). This to manually writing the code that I thought eventually could be generated (stubs of those auxiliary functions). What do you think?

$^1$ Unless 2 Handlers of the same name are defined in different packages and both used.

2023-05-10 01:06 UTC, ranchalp commented on pkg/trantor/system.go
> +	//<<<<<<< HEAD
Oh yeah I just commented part of the rebase there cause I was not sure at the time which o the two would fit. I bit that comment though. The rebasing went well, not too complicated anyways.

2023-05-10 01:09 UTC, ranchalp commented on pkg/orderers/internal/parts/goodcase/pbftgoodcase.go
We used to but you are right that it is not the case for `Propose` anymore. In any case, recall that exported functions in subfolders of `'module'/internal` can only be used by packages in the folder `'module'` and their submodules.

I will now go through each of the functions and verify whether they need to be exported or not here.

2023-05-10 02:25 UTC, ranchalp commented on pkg/orderers/internal/parts/goodcase/pbftgoodcase.go
> +// ============================================================
Done

2023-05-10 02:27 UTC, ranchalp commented on pkg/orderers/internal/common/pbftviewchangestate.go
> +	// in which case the value is set to a Preprepare with an empty certificate and the "aborted" flag set.
done

2023-05-10 02:28 UTC, ranchalp commented on pkg/orderers/internal/common/common.go
> +// pbftProposalState tracks the state of the pbftInstance related to proposing certificates.
done.

2023-05-10 02:30 UTC, ranchalp commented on pkg/orderers/internal/common/common.go
> +	// The segment governing this SB instance, specifying the leader, the set of sequence numbers, the buckets, etc.
Removed

2023-05-10 02:32 UTC, ranchalp commented on pkg/orderers/internal/parts/goodcase/pbftgoodcase.go
> +		"sn", sn)
Done

2023-05-10 02:32 UTC, ranchalp commented on pkg/orderers/internal/parts/goodcase/pbftgoodcase.go
> +func applyProposeTimeout(m dsl.Module, state *common.State, params *common.ModuleParams, moduleConfig common2.ModuleConfig, numProposals int, logger logging.Logger) error {
Agreed, `common2` was an artifact of automatic refactoring. Had in mind to fix that in a future PR. 

Fixing the headers now in this PR

2023-05-10 02:48 UTC, ranchalp commented
> Let's pick one way of approaching this per file. Either
> 
>     1. everything is in-line, i.e., inside the `Upon...` handler registration call, as an anonymous function, the way simple stuff like the the availability module (auxiliary functions are still encouraged, but the high-level logic of a handler would be directly inside the handler), or
> 
>     2. all handler registrations would be one-liners, simply referring to auxiliary handler functions _of the same name_1 (but with a lower-case first letter, to not export them). This to manually writing the code that I thought eventually could be generated (stubs of those auxiliary functions). What do you think?
> 
> 
> 1 Unless 2 Handlers of the same name are defined in different packages and both used.

This makes sense, except that for case 1. sometimes the entire handling of the `Upon...` event must be an auxiliary function, because it is code that could be called somewhere (an example of that is applying a prepare message, which must be process after buffer in the event of a view change). I think that in this case we should stick to 1. but leave `apply...` instead of approach 2. (to differentiate functions from approach 2. from functions that are in approach 1. but that happen to be used elsewhere. Weak opinition weakly held. What is your opinion?

2023-05-10 03:53 UTC, ranchalp commented on pkg/orderers/internal/common/pbftconfig.go
> +	EpochNr tt.EpochNr
Added issue #439

2023-05-10 03:56 UTC, ranchalp commented on pkg/orderers/internal/parts/goodcase/pbftgoodcase.go
> +func applyProposeTimeout(m dsl.Module, state *common.State, params *common.ModuleParams, moduleConfig common2.ModuleConfig, numProposals int, logger logging.Logger) error {
See #440 for the renaming

2023-05-10 03:57 UTC, ranchalp commented on pkg/orderers/internal/parts/catchup/catchup.go
> +	// process the missing committed certificate as its hash became available.
#439

2023-05-10 04:00 UTC, ranchalp commented
All comments converted to issues or resolved :)

2023-05-10 08:07 UTC, matejpavlovic approved these changes
Great job Alex!
I leave you the pleasure of clicking the "Merge" button :-)
(Just don't forget to leave a meaningful commit message of the squashed commits.)

Regarding the unified way of using handler functions, anything you said is fine with me. If a handler is also called indirectly (like applying a prepare message, or applying buffered messages) in a file where option 1. is used, I'll be happy with any of the following.
- Switching the whole file to option 2.
- Making an exception and defining just that function in option-2-style, with an option-2-name
- Defining just that function with a different name (like `apply...`)

We don't need to over-specify things, especially since there are many way more urgent issues to address. A style guide would be nice though, eventually, I'll add an issue for that.

2023-05-10 10:43 UTC, merged