Externalize Preprepare Validity checker
filecoin-project/mir pull request #494
Opened 2023-07-16 08:07 UTC by ranchalp

Given the extra PBFT instance we have for agreement with the checkpoint certificate, I had to work around some things that otherwise would have been left more general, but I think it is still quite good.

2023-07-16 08:11 UTC, ranchalp commented on protos/ordererpb/prepreparevaliditycheckerpb/prepreparevaliditycheckerpb.proto
deleted in later commit, This file sneaked in when git add on the folder. Sorry

2023-07-16 08:11 UTC, ranchalp commented on protos/proto_converter_tmp_3690055431/generator.go
deleted in later commit, This file sneaked in when git add on the folder. Sorry

2023-07-16 08:15 UTC, ranchalp commented on pkg/iss/iss.go
> +		// Instantiate a new PBFT orderer.
this comment has been removed in a later commit.

2023-07-16 08:16 UTC, ranchalp commented on pkg/orderers/factory.go
> +				if p.PvcId == "prepreparevaliditycheckerpermissive" { // this must change but that's the scope of a different PR
Comment removed, but note it.

2023-07-17 15:52 UTC, ranchalp commented
Note to reviewer: I will rebase from the checkpoint PR once merged so ignore the commits relevant to that should you review this before I merge :)

2023-07-17 15:52 UTC, ranchalp commented
Note to reviewer: I will rebase from the checkpoint PR once merged so ignore the commits relevant to that should you review this before I rebase :)

2023-07-17 17:57 UTC, matejpavlovic commented
Thanks for the PR! I'll review it when #493 is merged and this one rebased on top, it will be easier to think about it that way.

2023-07-22 19:14 UTC, matejpavlovic requested changes
Nice PR!
I only have one substantial comment (see below), the others are mostly nits.
Also, we'll eventually generalize this evne further, such that the validity checker is not specific to the PBFT protocol, but really just validates proposals (of any protocol). It will then be on the ordering protocol to figure out how to talk to the verifier.
But this is already going in that direction. Nice job!

(Again, I fixed some formatting and typo-level things, I'm pushing them directly.)

2023-07-23 08:45 UTC, ranchalp commented
>  Also, we'll eventually generalize this evne further, such that the validity checker is not specific to the PBFT protocol, but really just validates proposals (of any protocol). It will then be on the ordering protocol to figure out how to talk to the verifier.

Actually, the real generalization should be to a generic validity checker module (and factory), that takes generic data as bytes (or repeated bytes?) and has two events, check and checked (or analogous names). I thought about doing this for both the preprepare validity checker (the one in this PR) and the checkpoint validity checker ( #493 ), but in benefit of cleanliness using the benefits of the code generator instead of serializing/deserializing ourselves, I opted for this option. I definitely think once we resolve issue #433 we should opt for the generic validity checker module (and factory). @matejpavlovic

2023-07-23 08:47 UTC, ranchalp commented on protos/ordererpb/ordererpb.proto
> +  string      pvc_id           = 4;
I initially called it pvc (as the PR was submitted before merging the #493 ). Once we settled on a different name for #493 , I went here to change all instances of pvc to ppv. Seems like I missed this one. Resolved locally will submit with other comments.

2023-07-23 08:48 UTC, ranchalp commented on protos/ordererpb/ordererpb.proto
> +  string      pvc_id           = 4;
Oh In fact I did change it, this is just an old commit in the same PR.

2023-07-23 08:48 UTC, ranchalp commented on protos/ordererpb/pprepvalidatorpb/pprepvalidatorpb.proto
> +    Validatepreprepare validate_preprepare   = 1;
Locally changed for simplicity (also this is on an outdated commit so I cannot even commit the suggestion).

2023-07-23 08:49 UTC, ranchalp commented on protos/ordererpb/pprepvalidatorpb/pprepvalidatorpb.proto
> +message Validatepreprepare {
Locally changed for simplicity with commits

2023-07-23 08:51 UTC, ranchalp commented on pkg/orderers/common/prepreparevaliditychecker/api.go
> +	Check(preprepare *pbftpbtypes.Preprepare) error
Good catch. Changed

2023-07-23 08:51 UTC, ranchalp commented on pkg/orderers/common/prepreparevaliditychecker/prepreparevaliditychecker.go
> +	CVC  t.ModuleID
This was changed already in a later commit once #493 was merged.

2023-07-23 08:52 UTC, ranchalp commented on pkg/orderers/common/prepreparevaliditychecker/prepreparevaliditychecker.go
> +					validityChecker = NewCheckpointValidityChecker(hashImpl, chkpVerifier, p.Membership, issParams, logger)
Resolved already once I rebased in this PR.

2023-07-23 08:58 UTC, ranchalp commented on protos/ordererpb/pprepvalidatorpb/pprepvalidatorpb.proto
> +  uint64      validity_checker    = 1;
Done, thanks.

2023-07-23 09:18 UTC, ranchalp commented on pkg/iss/iss.go
> +				iss.moduleConfig.PPrepValidator.Then("permissive"),
This is irrelevant once previous comment resolved

2023-07-23 09:18 UTC, ranchalp commented on pkg/iss/iss.go
> +			))
Done :)

2023-07-23 09:20 UTC, ranchalp commented on pkg/orderers/factory.go
> +				if p.PpvModuleId == "prepreparevaliditycheckerpermissive" { // this must change but that's the scope of a different PR
You are absolutely right, I slipped that one, changed back to chkp validator. :)

2023-07-23 09:20 UTC, ranchalp commented on pkg/orderers/factory.go
> +				if p.PpvModuleId == "prepreparevaliditycheckerpermissive" { // this must change but that's the scope of a different PR
Thanks for the catch!!

2023-07-23 10:03 UTC, ranchalp commented
Changes addressed! :)

2023-07-23 19:50 UTC, matejpavlovic commented
Yes, I agree, that's what we should do eventually. I think that the checkpoint validity checker (#493) is good as it is, as it's a conceptually a different thing than validating propsals. The fact that some proposals happen to contain a checkpoint is rather coincidental. The one concrete proposal validity checker that happens to validate checkpoints might, of course, "outsource" part of the validation to the checkpoint validator (e.g., deserialize the checkpoint from the raw data, have that validated by another module, and then respond to the ordering protocol), but otherwise I think that the concepts should not mix.

2023-07-23 19:55 UTC, matejpavlovic approved these changes
Great job Alex!
I added one more commit with a little bit of minor polishing and a few comments.
If you agree with those changes, go ahead and merge! 🚀

2023-07-24 09:31 UTC, merged